# Generated by Django 4.2.4 on 2023-08-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_remove_user_id_number_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.employerprofile'),
        ),
    ]
